### ISSUE TITLE
Add link to deployed Heroku instance

### ISSUE THREAD

**Issue by Ryuno-Ki** [cvega21/fitness-tracking#2]
Similar to [how to add topics to a GitHub repository](https://docs.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics) you can add a website, that could be the deployed Heroku instance, for example.

This way, it's easier to look at what the code renders to.

**Comment by cvega21** [comment]
added the link now (cool-fitness-tracker.herokuapp.com/)
